// react-course-midali/corso-react/src/Login.tsx
const Login = () =>{
    return (
        <div className="row m-0 p-0 background">
          <div className="container py-5 text-center">
  <div className="row py-5">
    <div className="col-md-6">
        <form action="" className="border p-3 rounded shadow">
    <label htmlFor=""></label>
    <input type="email" required className="form-control" />
    <label htmlFor=""></label>
    <input type="password" required className="form-control" />
    <button className="btn m-1"> Login</button>
</form>
    </div>
    <div className="col-md-6">
<h1>Your absolute wonderful website</h1>
    </div>

  </div>
</div>  
        </div>



    )
}

export default Login;

// react-course-midali/angular-blogs-midali/src/app/components/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit{

  param:string=''
  form!:FormGroup
  formSignup!:FormGroup

  constructor(private activatedRoute:ActivatedRoute){
    this.activatedRoute.params.subscribe(params => {
      this.param=params['param']
    })
  }

  ngOnInit():void{

  }

  login():void{

  }
  signup():void{

  }
}

<div class="background p-0 m-0">
  <div class="container py-5 text-center">
  <div class="row py-5">
<div class="col-md-6"></div>
<div class="col-md-6">
  <form [formGroup]="form" class="border p-5 shadow rounded" *ngIf="param=='login'">
    <label class="p-2">Email</label><br>
    <input type="text" class="p-2 w-50"><br>
    <label class="p-2">Password</label><br>
    <input type="text" class="p-2 w-50"><br>
    <button class="btn p-3" (click)="login()">Login</button>
  </form>
  <form [formGroup]="formSignup" class="border p-5 shadow rounded" *ngIf="param=='signup'">
    <label class="p-2">Nome</label><br>
    <input type="text" class="p-2 w-50"><br>
    <label class="p-2">Cognome</label><br>
    <input type="text" class="p-2 w-50"><br>
    <label class="p-2">Email</label><br>
    <input type="text" class="p-2 w-50"><br>
    <label class="p-2">Password</label><br>
    <input type="text" class="p-2 w-50"><br>
    <label class="p-2">Ripeti Password</label><br>
    <input type="text" class="p-2 w-50"><br>
    <button class="btn p-3" (click)="signup()">Signup</button>
  </form>
</div>
  </div>
</div>
</div>
