// react-course-midali/angular-blogs-midali/src/app/components/nav/nav.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-nav',
  templateUrl: './nav.component.html',
  styleUrls: ['./nav.component.scss']
})
export class NavComponent {
authenticated:boolean=false
}

<nav class="p-3 bg-warning text-center">
  <div class="container">
    <div class="row">
<div class="col-md-6">
  <h2>Home</h2>
</div>
<div class="col-md-6">
  <h2 *ngIf="!authenticated">Login/Signup</h2>
  <h2 *ngIf="authenticated">Logout</h2>
</div>
    </div>
  </div>
</nav>

// react-course-midali/corso-react/src/nav.tsx
import { Link } from "react-router-dom";

const Nav = () =>{
    return(
<nav className="p-2 bg-yellow-500 text-dark text-center">
    <div className="row">
        <div className="col-md-4 p-2">
            <Link to={'/Home'}>Home</Link>
        </div>
        <div className="col-md-4 p-2">
            <Link to={'/Blog'}>Blog</Link>
        </div>
        <div className="col-md-4 p-2">
            <Link to={'/Login'}>Login</Link>
        </div>
    </div>
</nav>

    )
}

export default Nav;
